[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npx expo export:web"]

[start]
cmd = "npx serve web-build -s -p $PORT"

